dist: trusty
install: ./gradlew assemble
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
script:
  - ./gradlew build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: kalium-alkalio:TKKbLCQK8wW6HLPGfrGWyKUS
