// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package io.alkal.kalium.sns_sqs.tests.models.pb;

public final class Payment {
  private Payment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PaymentPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.alkal.kalium.kafka.tests.pb.PaymentPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>bool processed = 2;</code>
     * @return The processed.
     */
    boolean getProcessed();
  }
  /**
   * Protobuf type {@code io.alkal.kalium.kafka.tests.pb.PaymentPB}
   */
  public  static final class PaymentPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.alkal.kalium.kafka.tests.pb.PaymentPB)
      PaymentPBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PaymentPB.newBuilder() to construct.
    private PaymentPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PaymentPB() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PaymentPB();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PaymentPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              processed_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.alkal.kalium.sns_sqs.tests.models.pb.Payment.internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.alkal.kalium.sns_sqs.tests.models.pb.Payment.internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.class, io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCESSED_FIELD_NUMBER = 2;
    private boolean processed_;
    /**
     * <code>bool processed = 2;</code>
     * @return The processed.
     */
    public boolean getProcessed() {
      return processed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (processed_ != false) {
        output.writeBool(2, processed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (processed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, processed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB)) {
        return super.equals(obj);
      }
      io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB other = (io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getProcessed()
          != other.getProcessed()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + PROCESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getProcessed());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.alkal.kalium.kafka.tests.pb.PaymentPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.alkal.kalium.kafka.tests.pb.PaymentPB)
        io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.alkal.kalium.sns_sqs.tests.models.pb.Payment.internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.alkal.kalium.sns_sqs.tests.models.pb.Payment.internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.class, io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.Builder.class);
      }

      // Construct using io.alkal.kalium.kafka.tests.pb.Payment.PaymentPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        processed_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.alkal.kalium.sns_sqs.tests.models.pb.Payment.internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_descriptor;
      }

      @java.lang.Override
      public io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB getDefaultInstanceForType() {
        return io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.getDefaultInstance();
      }

      @java.lang.Override
      public io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB build() {
        io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB buildPartial() {
        io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB result = new io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB(this);
        result.id_ = id_;
        result.processed_ = processed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB) {
          return mergeFrom((io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB other) {
        if (other == io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getProcessed() != false) {
          setProcessed(other.getProcessed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private boolean processed_ ;
      /**
       * <code>bool processed = 2;</code>
       * @return The processed.
       */
      public boolean getProcessed() {
        return processed_;
      }
      /**
       * <code>bool processed = 2;</code>
       * @param value The processed to set.
       * @return This builder for chaining.
       */
      public Builder setProcessed(boolean value) {
        
        processed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool processed = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessed() {
        
        processed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.alkal.kalium.kafka.tests.pb.PaymentPB)
    }

    // @@protoc_insertion_point(class_scope:io.alkal.kalium.kafka.tests.pb.PaymentPB)
    private static final io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB();
    }

    public static io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaymentPB>
        PARSER = new com.google.protobuf.AbstractParser<PaymentPB>() {
      @java.lang.Override
      public PaymentPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PaymentPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PaymentPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentPB> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayment.proto\022\036io.alkal.kalium.kafka.t" +
      "ests.pb\"*\n\tPaymentPB\022\n\n\002id\030\001 \001(\t\022\021\n\tproc" +
      "essed\030\002 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_alkal_kalium_kafka_tests_pb_PaymentPB_descriptor,
        new java.lang.String[] { "Id", "Processed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
