package io.alkal.kalium.sns_sqs.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.alkal.kalium.sns_sqs.serdes.AvroSerializer;
import io.alkal.kalium.sns_sqs.tests.models.avro.PaymentAV;
import org.junit.Test;

import java.io.IOException;
import java.util.Base64;

import static org.junit.Assert.*;


public class AvroSerializerTest {

    public static final String payment_id = "cdb0dfb9-396d-4269-bfa4-8408211b5e3d";
    public static final PaymentAV payment = PaymentAV.newBuilder().setId(payment_id).setProcessed(false).build();
    public static String validSerializedPayment;

    static {
        try {
            validSerializedPayment = Base64.getEncoder().encodeToString(payment.toByteBuffer().array());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private AvroSerializer target = new AvroSerializer();


    @Test
    public void testSerialize_whenObjectNull_shouldReturnNullObject() {
        Object o = target.serialize(null);
        assertNull(o);
    }


    @Test
    public void testSerializePayment_shouldReturnCorrectBytes() {
        String base64 = target.serialize(payment);
        assertTrue("byte[] is empty", base64 != null && base64.length() > 0);
        assertEquals(validSerializedPayment, target.serialize(payment));
    }
}
