package io.alkal.kalium.sns_sqs.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.fasterxml.jackson.databind.ObjectMapper;
import io.alkal.kalium.sns_sqs.serdes.JsonDeSerializer;
import io.alkal.kalium.sns_sqs.serdes.SerializationException;
import io.alkal.kalium.sns_sqs.tests.models.pojo.Payment;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

import java.io.IOException;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;


public class JsonDeSerializerTest {

    public static final String payment_id = "cdb0dfb9-396d-4269-bfa4-8408211b5e3d";
    public static final String validSerializedPayment = Base64.getEncoder()
            .encodeToString(new String("{\"processed\":false,\"id\":\"" + payment_id + "\"}").getBytes());
    public static final String validTopic = "payment";

    private JsonDeSerializer target;

    private ObjectMapper objectMapper;

    @Before
    public void setup() {
        objectMapper = mock(ObjectMapper.class);
        target = new JsonDeSerializer(objectMapper);
    }

    @Test(expected = RuntimeException.class)
    public void testConfigure_shouldThrowAnException_whenTopicToClassMapIsNull() throws InterruptedException {
        target.configure(null);
    }


    @Test(expected = SerializationException.class)
    public void testDeserialize_whenTopicIsNull_shouldThrowSerializationException() {
        target.deserialize(null, validSerializedPayment);
    }

    @Test(expected = SerializationException.class)
    public void testDeserialize_whenTopicIsEmptyString_shouldThrowSerializationException() {
        target.deserialize("", validSerializedPayment);
    }

    @Test(expected = SerializationException.class)
    public void testDeserialize_whenTopicIsNotInTopicToClassMap_shouldThrowSerializationException() {
        Map<String, Class<?>> topicToClassMap = new HashMap<>();
        target.configure(topicToClassMap);

        target.deserialize(validTopic, validSerializedPayment);
    }

    @Test(expected = SerializationException.class)
    public void testDeserialize_whenNoClassIsMappedInTopicToClassMap_shouldThrowSerializationException() {
        Map<String, Class<?>> topicToClassMap = new HashMap<>();
        topicToClassMap.put("payment", null);
        target.configure(topicToClassMap);

        target.deserialize(validTopic, validSerializedPayment);
    }

    @Test(expected = SerializationException.class)
    public void testDeserialize_whenObjectMapperThrowsException_shouldThrowSerializationException() throws Exception {
        Mockito.when(objectMapper.readValue(any(byte[].class), any(Class.class))).thenThrow(new IOException());
        target.configure(createValidTopicToClassMap());
        target.deserialize(validTopic, validSerializedPayment);
    }

    @Test
    public void testDeserialize_whenBase64StringIsNull_shouldReturnNullObject() {
        target.configure(createValidTopicToClassMap());
        Object o = target.deserialize(validTopic, null);
        assertNull(o);
    }

    @Test
    public void testDeserialize_whenBase64StringIsEmpty_shouldReturnNullObject() {
        target.configure(createValidTopicToClassMap());
        Object o = target.deserialize(validTopic, "");
        assertNull(o);
    }

    @Test
    public void testDeserialize_shouldReturnPaymentObject() {
        target = new JsonDeSerializer(new ObjectMapper());
        target.configure(createValidTopicToClassMap());
        Object o = target.deserialize(validTopic, validSerializedPayment);
        assertTrue(o instanceof Payment);
    }


    private static Map<String, Class<?>> createValidTopicToClassMap() {
        Map<String, Class<?>> topicToClassMap = new HashMap<>();
        topicToClassMap.put("payment", Payment.class);
        return topicToClassMap;
    }


}
