package io.alkal.kalium.sns_sqs.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.alkal.kalium.internals.QueueListener;
import io.alkal.kalium.sns_sqs.KaliumSnsSqsQueueAdapter;
import io.alkal.kalium.sns_sqs.SnsService;
import io.alkal.kalium.sns_sqs.tests.models.pojo.Payment;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;

import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class KaliumSnsSqsQueueAdapterTest {

    private KaliumSnsSqsQueueAdapter target;
    private QueueListener queueListener;

    @Before
    public void setup() {
        target = new KaliumSnsSqsQueueAdapter("mykey", "mysecret", "us-west-1");
        queueListener = spy(QueueListener.class);
        target.setQueueListener(queueListener);
    }

    @Test(expected = RuntimeException.class)
    public void testStart_shouldThrowExceptionIfSomeAwsCredentialsAreMissing() {
        target = new KaliumSnsSqsQueueAdapter(null, "mysecret", "us-west-1");
        target.start();
    }

    @Test
    public void testStart_shouldConsumeReactionIdsToObjectTypesMapFromMainQueueListener() {

        target.start();
        verify(queueListener).getReactionIdsToObjectTypesMap();
    }

    @Test(expected = RuntimeException.class)
    public void testPost_shouldThrowException_whenCalledBeforeStart() {
        target.post(new Payment());
    }

}
