package io.alkal.kalium.sns_sqs.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.alkal.kalium.sns_sqs.ProtoUtils;
import io.alkal.kalium.sns_sqs.tests.models.pb.Payment;
import org.junit.Test;

import java.lang.reflect.Method;

import static org.junit.Assert.*;


public class ProtoUtilsTest {


    @Test(expected = NoSuchMethodException.class)
    public void testGetParseFromMethod_shouldThrowException_whenNoProtoClassIsUsed() throws NoSuchMethodException {
        ProtoUtils.getParseFromMethod(String.class);
    }

    @Test
    public void testGetParseFromMethod_shouldReturnParseFromMethod_whenProtoClassIsUsed() throws NoSuchMethodException {
        Method m = ProtoUtils.getParseFromMethod(Payment.PaymentPB.class);
        assertEquals("parseFrom", m.getName());
    }


    @Test
    public void testIsProtoClass_shouldReturnTheCorrectAnswer() {
        assertTrue(ProtoUtils.isProtoClass(Payment.PaymentPB.class));
        assertFalse(ProtoUtils.isProtoClass(io.alkal.kalium.sns_sqs.tests.models.pojo.Payment.class));
    }


}
