package io.alkal.kalium.sns_sqs.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.alkal.kalium.sns_sqs.serdes.ProtobufDeSerializer;
import io.alkal.kalium.sns_sqs.serdes.SerializationException;
import org.junit.Test;

import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;


public class ProtobufDeSerializerTest {

    public static final String payment_id = "cdb0dfb9-396d-4269-bfa4-8408211b5e3d";
    public static final String validSerializedPayment =
            Base64.getEncoder().encodeToString(io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.newBuilder()
                    .setId(payment_id).setProcessed(false).build().toByteArray());
    public static final String validTopic = "payment";


    private ProtobufDeSerializer target = new ProtobufDeSerializer();

    @Test(expected = RuntimeException.class)
    public void testConfigure_shouldThrowAnException_whenPropsHasNoTopicToClassMapValue() throws InterruptedException {
        target.configure(null);
    }


    @Test(expected = SerializationException.class)
    public void testDeserialize_whenTopicIsNull_shouldThrowSerializationException() {

        target.deserialize(null, validSerializedPayment);
    }

    @Test(expected = SerializationException.class)
    public void testDeserialize_whenTopicIsEmptyString_shouldThrowSerializationException() {
        target.deserialize("", validSerializedPayment);
    }

    @Test(expected = SerializationException.class)
    public void testDeserialize_whenTopicIsNotInTopicToClassMap_shouldThrowSerializationException() {
        Map<String, Class<?>> topicToClassMap = new HashMap<>();
        target.configure(topicToClassMap);

        target.deserialize(validTopic, validSerializedPayment);
    }

    @Test(expected = SerializationException.class)
    public void testDeserialize_whenNoClassIsMappedInTopicToClassMap_shouldThrowSerializationException() {
        Map<String, Class<?>> topicToClassMap = new HashMap<>();
        topicToClassMap.put("payment", null);
        target.configure(topicToClassMap);

        target.deserialize(validTopic, validSerializedPayment);
    }

    @Test
    public void testDeserialize_whenBytesNull_shouldReturnNullObject() {
        target.configure(createValidTopicToClassMap());
        Object o = target.deserialize(validTopic, null);
        assertNull(o);
    }

    @Test
    public void testDeserialize_whenBytesIsEmpty_shouldReturnNullObject() {
        target.configure(createValidTopicToClassMap());
        Object o = target.deserialize(validTopic, "");
        assertNull(o);
    }

    @Test
    public void testDeserialize_shouldReturnPaymentObject() {
        target.configure(createValidTopicToClassMap());
        Object o = target.deserialize(validTopic, validSerializedPayment);
        assertTrue(o instanceof io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB);
    }

    private static Map<String, Class<?>> createValidTopicToClassMap() {
        Map<String, Class<?>> topicToClassMap = new HashMap<>();
        topicToClassMap.put("payment", io.alkal.kalium.sns_sqs.tests.models.pb.Payment.PaymentPB.class);
        return topicToClassMap;
    }


}
